
auth.token=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

defaults.org=modu-taxi
defaults.project=react-native

defaults.url=https://sentry.io/
